### ISSUE TITLE
想问一下测试的时候出现这个问题需要怎么修改呢

### ISSUE THREAD

**Issue by Charles-9802** [limaosen0/DMGNN#11]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    p.start()
  File "/media/ubuntu/data2/DMGNN-master/h36m-short/processor/processor.py", line 126, in start
    self.test()
  File "/media/ubuntu/data2/DMGNN-master/h36m-short/processor/recognition.py", line 252, in test
    self.mean_MAE_select[iter_time] = np.mean((self.MAE_tensor[iter_time, :, 1]+
AttributeError: 'REC_Processor' object has no attribute 'mean_MAE_select'

**Comment by Cindy0532** [comment]
你好，我遇到了跟你同样的问题，请问你这个问题解决了吗？能否分享一下，谢谢？

**Comment by chengpengyan** [comment]
你好，我遇到了跟你同样的问题，请问你这个问题解决了吗？能否分享一下，谢谢？

**Comment by Cindy0532** [comment]
对不起，我没有解决这个问题
