### ISSUE TITLE
human3.6数据集提问

### ISSUE THREAD

**Issue by helloful** [limaosen0/DMGNN#9]
您好，在您的paper中，讲到human3.6有32个关节点，但是您代码中的数据并不是表示关节点的三维坐标，而是表示旋转向量；其次，您的代码中，您训练后的模型并没有完整的提供99个数据，训练模型仅仅输出了30个数据，请问您是如何可视化最后的预测结果的？得到您paper中的图的呢？

**Comment by Charles-9802** [comment]
您好，请问您现在代码复现成功了吗？复现的时候有没有遇到这个问题呢，求教谢谢！
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    p.start()
  File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-short\processor\processor.py", line 126, in start
    self.test()
  File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-short\processor\recognition.py", line 255, in test
    self.MAE_tensor[iter_time, :, 9])/4)
AttributeError: 'REC_Processor' object has no attribute 'mean_MAE_select'

**Comment by helloful** [comment]
我复现了啊，其实作者的代码中，提供了torchlight,照着安装一下就好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 晚上8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [limaosen0/DMGNN] human3.6数据集提问 (#9)





 
您好，请问您现在代码复现成功了吗？复现的时候有没有遇到这个问题呢，求教谢谢！
 Traceback (most recent call last):
 File "main.py", line 23, in 
 p.start()
 File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-short\processor\processor.py", line 126, in start
 self.test()
 File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-short\processor\recognition.py", line 255, in test
 self.MAE_tensor[iter_time, :, 9])/4)
 AttributeError: 'REC_Processor' object has no attribute 'mean_MAE_select'

**Comment by Charles-9802** [comment]
好的谢谢

**Comment by Cindy0532** [comment]
我运行这个的时候，也出现了跟你同样的问题。请问你解决了吗？我用Google colab 按照作者的指令安装，在第一步GPU那里就出错了。然后我直接尝试运行已保存的ｍｏｄｅｌ，　就出现了跟你一样的运行报错结果。



> 您好，请问您现在代码复现成功了吗？复现的时候有没有遇到这个问题呢，求教谢谢！
> Traceback (most recent call last):
> File "main.py", line 23, in
> p.start()
> File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-short\processor\processor.py", line 126, in start
> self.test()
> File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-short\processor\recognition.py", line 255, in test
> self.MAE_tensor[iter_time, :, 9])/4)
> AttributeError: 'REC_Processor' object has no attribute 'mean_MAE_select'
